"""Domain model for the Ramp Team Flight Optimizer."""

from ramp_optimizer.config import (
    DEFAULT_POSITION_ROLE_MAPPINGS,
    OptimizerConfig,
    TeamWorkImportConfig,
)
from ramp_optimizer.enums import (
    BreakStatus,
    EligibilityReason,
    FlightType,
    IssueSeverity,
    OperationalRole,
    OptimizationStatus,
    Qualification,
    StaffingStatus,
    WarningCode,
    WarningSeverity,
)
from ramp_optimizer.eligibility import (
    assess_employee_flight_eligibility,
    eligible_shifts_for_interval,
    employee_is_available_for_interval,
    role_is_assignment_eligible,
)
from ramp_optimizer.intervals import InvalidIntervalError, intervals_overlap
from ramp_optimizer.models import (
    CandidateAssignment,
    Employee,
    EmployeeShift,
    EligibilityAssessment,
    EmployeeScheduleResult,
    FairnessMetrics,
    Flight,
    FlightAssignmentResult,
    FixedAssignment,
    ImportIssue,
    ObjectiveValue,
    OperationalDay,
    OptimizationAttemptSummary,
    OptimizationResult,
    ScheduleWarning,
    ScheduleImportResult,
    ShiftImportRecord,
    VacancyRecord,
)
from ramp_optimizer.staffing import StaffingRequirements, staffing_requirements_for
from ramp_optimizer.timing import (
    FlightDerivationError,
    FlightNumberParseError,
    FlightOperationalFacts,
    classify_flight_type,
    derive_flight_operational_facts,
    derive_work_window,
    parse_numeric_flight_number,
)
from ramp_optimizer.validation import (
    InputValidationError,
    ValidationIssue,
    validate_config,
    validate_operational_day,
    validate_or_raise,
    validate_teamwork_import_config,
)
from ramp_optimizer.candidates import build_candidate_assignments
from ramp_optimizer.teamwork_import import (
    import_teamwork_schedule,
    normalize_header,
    normalize_identity_name,
    normalize_position_label,
    position_mapping,
)

__all__ = [
    "assess_employee_flight_eligibility",
    "BreakStatus",
    "build_candidate_assignments",
    "CandidateAssignment",
    "DEFAULT_POSITION_ROLE_MAPPINGS",
    "Employee",
    "EmployeeShift",
    "EmployeeScheduleResult",
    "EligibilityAssessment",
    "EligibilityReason",
    "eligible_shifts_for_interval",
    "employee_is_available_for_interval",
    "FairnessMetrics",
    "Flight",
    "FlightAssignmentResult",
    "FixedAssignment",
    "FlightDerivationError",
    "FlightNumberParseError",
    "FlightOperationalFacts",
    "FlightType",
    "ImportIssue",
    "InputValidationError",
    "InvalidIntervalError",
    "import_teamwork_schedule",
    "ObjectiveValue",
    "OperationalRole",
    "OperationalDay",
    "OptimizationAttemptSummary",
    "OptimizationResult",
    "OptimizationStatus",
    "OptimizerConfig",
    "Qualification",
    "classify_flight_type",
    "derive_flight_operational_facts",
    "derive_work_window",
    "intervals_overlap",
    "normalize_header",
    "normalize_identity_name",
    "normalize_position_label",
    "position_mapping",
    "parse_numeric_flight_number",
    "role_is_assignment_eligible",
    "ScheduleImportResult",
    "ScheduleWarning",
    "ShiftImportRecord",
    "StaffingRequirements",
    "StaffingStatus",
    "staffing_requirements_for",
    "TeamWorkImportConfig",
    "ValidationIssue",
    "WarningCode",
    "WarningSeverity",
    "VacancyRecord",
    "validate_config",
    "validate_operational_day",
    "validate_or_raise",
    "validate_teamwork_import_config",
]
