"""Domain model for the Ramp Team Flight Optimizer."""

from ramp_optimizer.config import (
    DEFAULT_POSITION_ROLE_MAPPINGS,
    OptimizerConfig,
    TeamWorkImportConfig,
)
from ramp_optimizer.enums import (
    BreakStatus,
    FlightType,
    IssueSeverity,
    OperationalRole,
    OptimizationStatus,
    Qualification,
    StaffingStatus,
    WarningCode,
    WarningSeverity,
)
from ramp_optimizer.eligibility import (
    eligible_shifts_for_interval,
    employee_is_available_for_interval,
    role_is_assignment_eligible,
)
from ramp_optimizer.models import (
    Employee,
    EmployeeShift,
    EmployeeScheduleResult,
    FairnessMetrics,
    Flight,
    FlightAssignmentResult,
    ImportIssue,
    ObjectiveValue,
    OperationalDay,
    OptimizationAttemptSummary,
    OptimizationResult,
    ScheduleWarning,
    ScheduleImportResult,
    VacancyRecord,
)
from ramp_optimizer.validation import (
    InputValidationError,
    ValidationIssue,
    validate_config,
    validate_operational_day,
    validate_or_raise,
    validate_teamwork_import_config,
)
from ramp_optimizer.teamwork_import import (
    import_teamwork_schedule,
    normalize_header,
    normalize_identity_name,
    normalize_position_label,
    position_mapping,
)

__all__ = [
    "BreakStatus",
    "DEFAULT_POSITION_ROLE_MAPPINGS",
    "Employee",
    "EmployeeShift",
    "EmployeeScheduleResult",
    "eligible_shifts_for_interval",
    "employee_is_available_for_interval",
    "FairnessMetrics",
    "Flight",
    "FlightAssignmentResult",
    "FlightType",
    "ImportIssue",
    "InputValidationError",
    "import_teamwork_schedule",
    "ObjectiveValue",
    "OperationalRole",
    "OperationalDay",
    "OptimizationAttemptSummary",
    "OptimizationResult",
    "OptimizationStatus",
    "OptimizerConfig",
    "Qualification",
    "normalize_header",
    "normalize_identity_name",
    "normalize_position_label",
    "position_mapping",
    "role_is_assignment_eligible",
    "ScheduleImportResult",
    "ScheduleWarning",
    "StaffingStatus",
    "TeamWorkImportConfig",
    "ValidationIssue",
    "WarningCode",
    "WarningSeverity",
    "VacancyRecord",
    "validate_config",
    "validate_operational_day",
    "validate_or_raise",
    "validate_teamwork_import_config",
]
