"""Domain model for the Ramp Team Flight Optimizer."""

from ramp_optimizer.config import (
    DEFAULT_POSITION_ROLE_MAPPINGS,
    OptimizerConfig,
    TeamWorkImportConfig,
)
from ramp_optimizer.enums import (
    BreakStatus,
    EmergencyLeadReason,
    EmergencyPassDisposition,
    EmergencyStaffingStatus,
    EligibilityReason,
    FlightType,
    IssueSeverity,
    OperationalRole,
    OptimizationStatus,
    OperationalReadinessStatus,
    Qualification,
    StaffingStatus,
    WarningCode,
    WarningSeverity,
)
from ramp_optimizer.eligibility import (
    assess_employee_flight_eligibility,
    eligible_shifts_for_interval,
    employee_is_available_for_interval,
    role_is_assignment_eligible,
)
from ramp_optimizer.intervals import InvalidIntervalError, intervals_overlap
from ramp_optimizer.models import (
    CandidateAssignment,
    ContinuityMetrics,
    ContinuityTransitionResult,
    Employee,
    EmployeeShift,
    EligibilityAssessment,
    EmployeeScheduleResult,
    EmergencyLeadAssignmentResult,
    FairnessMetrics,
    Flight,
    FlightAssignmentResult,
    FixedAssignment,
    ImportIssue,
    ObjectiveValue,
    OperationalDay,
    OptimizationAttemptSummary,
    OptimizationResult,
    ScheduleSummary,
    ScheduleWarning,
    ScheduleImportResult,
    ShiftImportRecord,
    VacancyRecord,
)
from ramp_optimizer.optimizer import (
    optimize_flight_assignments,
    optimize_minimum_staffing,
)
from ramp_optimizer.reporting import format_optimization_report
from ramp_optimizer.sample_data import (
    SAMPLE_DATE,
    SAMPLE_SCENARIO_NAMES,
    SAMPLE_TIMEZONE,
    SampleScenario,
    build_emergency_lead_scenario,
    build_normal_scenario,
    build_sample_scenario,
    build_staffing_shortage_scenario,
)
from ramp_optimizer.staffing import StaffingRequirements, staffing_requirements_for
from ramp_optimizer.timing import (
    FlightDerivationError,
    FlightNumberParseError,
    FlightOperationalFacts,
    classify_flight_type,
    derive_flight_operational_facts,
    derive_work_window,
    parse_numeric_flight_number,
)
from ramp_optimizer.validation import (
    InputValidationError,
    ValidationIssue,
    validate_config,
    validate_operational_day,
    validate_or_raise,
    validate_teamwork_import_config,
)
from ramp_optimizer.workload import (
    WorkloadConfigurationError,
    adjusted_assignment_workload_units,
    scaled_workload_factors,
    workload_unit_scale,
    workload_units_to_public_value,
)
from ramp_optimizer.candidates import build_candidate_assignments
from ramp_optimizer.teamwork_import import (
    import_teamwork_schedule,
    normalize_header,
    normalize_identity_name,
    normalize_position_label,
    position_mapping,
)

__all__ = [
    "assess_employee_flight_eligibility",
    "adjusted_assignment_workload_units",
    "BreakStatus",
    "build_candidate_assignments",
    "build_emergency_lead_scenario",
    "build_normal_scenario",
    "build_sample_scenario",
    "build_staffing_shortage_scenario",
    "CandidateAssignment",
    "ContinuityMetrics",
    "ContinuityTransitionResult",
    "DEFAULT_POSITION_ROLE_MAPPINGS",
    "Employee",
    "EmployeeShift",
    "EmployeeScheduleResult",
    "EmergencyLeadAssignmentResult",
    "EmergencyLeadReason",
    "EmergencyPassDisposition",
    "EmergencyStaffingStatus",
    "EligibilityAssessment",
    "EligibilityReason",
    "eligible_shifts_for_interval",
    "employee_is_available_for_interval",
    "FairnessMetrics",
    "Flight",
    "FlightAssignmentResult",
    "FixedAssignment",
    "FlightDerivationError",
    "FlightNumberParseError",
    "FlightOperationalFacts",
    "FlightType",
    "ImportIssue",
    "InputValidationError",
    "InvalidIntervalError",
    "import_teamwork_schedule",
    "ObjectiveValue",
    "OperationalRole",
    "OperationalDay",
    "OptimizationAttemptSummary",
    "OptimizationResult",
    "OptimizationStatus",
    "OperationalReadinessStatus",
    "OptimizerConfig",
    "optimize_flight_assignments",
    "optimize_minimum_staffing",
    "Qualification",
    "format_optimization_report",
    "classify_flight_type",
    "derive_flight_operational_facts",
    "derive_work_window",
    "intervals_overlap",
    "normalize_header",
    "normalize_identity_name",
    "normalize_position_label",
    "position_mapping",
    "parse_numeric_flight_number",
    "role_is_assignment_eligible",
    "SAMPLE_DATE",
    "SAMPLE_SCENARIO_NAMES",
    "SAMPLE_TIMEZONE",
    "SampleScenario",
    "ScheduleImportResult",
    "ScheduleSummary",
    "ScheduleWarning",
    "ShiftImportRecord",
    "StaffingRequirements",
    "StaffingStatus",
    "staffing_requirements_for",
    "scaled_workload_factors",
    "TeamWorkImportConfig",
    "ValidationIssue",
    "WarningCode",
    "WarningSeverity",
    "WorkloadConfigurationError",
    "workload_unit_scale",
    "workload_units_to_public_value",
    "VacancyRecord",
    "validate_config",
    "validate_operational_day",
    "validate_or_raise",
    "validate_teamwork_import_config",
]
