/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/imports/combine': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Combine Imports */
    post: operations['combine_imports_api_v1_imports_combine_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/imports/operational-days/{day_id}/readiness': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readiness */
    get: operations['readiness_api_v1_imports_operational_days__day_id__readiness_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/imports/daily-flight-log': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upload Flights */
    post: operations['upload_flights_api_v1_imports_daily_flight_log_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/imports/teamwork-employee-schedule': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upload Schedule */
    post: operations['upload_schedule_api_v1_imports_teamwork_employee_schedule_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/imports/{import_id}/preview': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Import */
    get: operations['get_import_api_v1_imports__import_id__preview_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/imports/{import_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Import */
    get: operations['get_import_api_v1_imports__import_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/imports/{import_id}/revisions/{revision}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Revision */
    get: operations['get_revision_api_v1_imports__import_id__revisions__revision__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/imports/{import_id}/corrections': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Correct Import */
    post: operations['correct_import_api_v1_imports__import_id__corrections_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/imports/{import_id}/confirm': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Confirm Import */
    post: operations['confirm_import_api_v1_imports__import_id__confirm_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/operational-days/{day}/drafts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create */
    post: operations['create_api_v1_operational_days__day__drafts_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/operational-days/{day}/versions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Listing */
    get: operations['listing_api_v1_operational_days__day__versions_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/operational-day-versions/{version_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get */
    get: operations['get_api_v1_operational_day_versions__version_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/operational-day-versions/{version_id}/revisions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revise */
    post: operations['revise_api_v1_operational_day_versions__version_id__revisions_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/optimization-jobs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create */
    post: operations['create_api_v1_optimization_jobs_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/optimization-jobs/{job_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Status */
    get: operations['status_api_v1_optimization_jobs__job_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/optimization-jobs/{job_id}/progress': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Progress */
    get: operations['progress_api_v1_optimization_jobs__job_id__progress_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/optimization-jobs/{job_id}/cancel': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cancel */
    post: operations['cancel_api_v1_optimization_jobs__job_id__cancel_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/optimization-jobs/{job_id}/result': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Result */
    get: operations['result_api_v1_optimization_jobs__job_id__result_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations['health_api_v1_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/version': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Package Version */
    get: operations['package_version_api_v1_version_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/operational-days/validate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Validate Day */
    post: operations['validate_day_api_v1_operational_days_validate_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/optimizations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Optimize */
    post: operations['optimize_api_v1_optimizations_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/operational-days': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Stored Days */
    get: operations['list_stored_days_api_v1_operational_days_get'];
    put?: never;
    /** Create Stored Day */
    post: operations['create_stored_day_api_v1_operational_days_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/operational-days/{operational_day_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Stored Day */
    get: operations['get_stored_day_api_v1_operational_days__operational_day_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/operational-days/{operational_day_id}/optimizations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Optimize Stored Day */
    post: operations['optimize_stored_day_api_v1_operational_days__operational_day_id__optimizations_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/operational-days/{operational_day_id}/optimization-runs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Stored Runs */
    get: operations['list_stored_runs_api_v1_operational_days__operational_day_id__optimization_runs_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/optimization-runs/{optimization_run_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Stored Run */
    get: operations['get_stored_run_api_v1_optimization_runs__optimization_run_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Body_upload_flights_api_v1_imports_daily_flight_log_post */
    Body_upload_flights_api_v1_imports_daily_flight_log_post: {
      /** Workbook */
      workbook: string;
      /** Metadata */
      metadata: string;
    };
    /** Body_upload_schedule_api_v1_imports_teamwork_employee_schedule_post */
    Body_upload_schedule_api_v1_imports_teamwork_employee_schedule_post: {
      /**
       * Workbook
       * @description TeamWork .xlsx workbook
       */
      workbook: string;
      /**
       * Metadata
       * @description JSON ImportMetadataRequest: operational_date, authoritative roster, optional config
       */
      metadata: string;
    };
    /**
     * BreakStatus
     * @description Outcome of the bracketed between-assignment break evaluation.
     * @enum {string}
     */
    BreakStatus:
      'NOT_APPLICABLE' | 'NOT_EVALUABLE_BETWEEN_ASSIGNMENTS' | 'SATISFIED' | 'UNSATISFIED';
    /** CombineImportsRequest */
    CombineImportsRequest: {
      /**
       * Employee Import Id
       * Format: uuid
       */
      employee_import_id: string;
      /**
       * Flight Import Id
       * Format: uuid
       */
      flight_import_id: string;
    };
    /** ConfirmImportRequest */
    ConfirmImportRequest: {
      /** Revision */
      revision: number;
    };
    /** ContinuityMetricsResponse */
    ContinuityMetricsResponse: {
      /** Eligible Transition Count */
      eligible_transition_count: number;
      /** Total Retained Employee Transitions */
      total_retained_employee_transitions: number;
      /** Average Retained Employees Per Transition */
      average_retained_employees_per_transition: number;
      /** Strongest Retention Count */
      strongest_retention_count: number;
      strongest_transition: components['schemas']['ContinuityTransitionResponse'] | null;
      /** Transitions */
      transitions: components['schemas']['ContinuityTransitionResponse'][];
    };
    /** ContinuityTransitionResponse */
    ContinuityTransitionResponse: {
      previous_flight: components['schemas']['FlightResponse'];
      next_flight: components['schemas']['FlightResponse'];
      /** Retained Employee Ids */
      retained_employee_ids: string[];
      /** Retention Count */
      retention_count: number;
    };
    /** CorrectionsRequest */
    CorrectionsRequest: {
      /** Revision */
      revision: number;
      /** Corrections */
      corrections: components['schemas']['RowCorrectionRequest'][];
    };
    /** DraftRequest */
    DraftRequest: {
      /** Idempotency Key */
      idempotency_key: string;
      /** Source Snapshot Id */
      source_snapshot_id?: string | null;
      /** Source Version Id */
      source_version_id?: string | null;
      /** Reason */
      reason?: string | null;
    };
    /** EmergencyLeadAssignmentResponse */
    EmergencyLeadAssignmentResponse: {
      /** Employee Id */
      employee_id: string;
      flight: components['schemas']['FlightResponse'];
      /** Reasons */
      reasons: components['schemas']['EmergencyLeadReason'][];
      /** Message */
      message: string;
    };
    /**
     * EmergencyLeadReason
     * @description Measurable critical value supplied by one Lead assignment.
     * @enum {string}
     */
    EmergencyLeadReason: 'MINIMUM_STAFFING' | 'PUSH_QUALIFICATION' | 'CLOSE_QUALIFICATION';
    /**
     * EmergencyPassDisposition
     * @description Unambiguous disposition of the optional emergency solve.
     * @enum {string}
     */
    EmergencyPassDisposition:
      | 'NOT_ENABLED'
      | 'NOT_NEEDED'
      | 'NOT_ATTEMPTED_NO_USABLE_SCHEDULE'
      | 'ATTEMPTED_AND_ADOPTED'
      | 'ATTEMPTED_ADOPTED_WITH_REMAINING_SHORTAGE'
      | 'ATTEMPTED_NOT_ADOPTED_UNUSABLE'
      | 'ATTEMPTED_NOT_ADOPTED_WORSE'
      | 'ATTEMPTED_NOT_ADOPTED_NO_IMPROVEMENT';
    /**
     * EmergencyStaffingStatus
     * @description Operational outcome of the optional emergency-Lead fallback.
     * @enum {string}
     */
    EmergencyStaffingStatus:
      'NORMAL_SCHEDULE' | 'LEAD_ASSISTED_SCHEDULE' | 'CRITICAL_SHORTAGE_REMAINS';
    /** EmployeeRequest */
    EmployeeRequest: {
      /** Employee Id */
      employee_id: string;
      /** Name */
      name: string;
      /**
       * Qualifications
       * @default []
       */
      qualifications: components['schemas']['Qualification'][];
      /**
       * Enabled
       * @default true
       */
      enabled: boolean;
    };
    /** EmployeeScheduleResponse */
    EmployeeScheduleResponse: {
      /** Employee Id */
      employee_id: string;
      /** Assigned Flights */
      assigned_flights: components['schemas']['FlightResponse'][];
      /** Flight Count */
      flight_count: number;
      /** Mainline Flight Count */
      mainline_flight_count: number;
      /** Express Flight Count */
      express_flight_count: number;
      /** Three Person Flight Count */
      three_person_flight_count: number;
      /** Longest Consecutive Streak */
      longest_consecutive_streak: number;
      break_status: components['schemas']['BreakStatus'];
      /** Adjusted Workload */
      adjusted_workload: number | null;
      /** Scheduled Shift Minutes */
      scheduled_shift_minutes: number | null;
      /** Proportional Target Flight Count */
      proportional_target_flight_count: number | null;
      /** Shift Adjusted Deviation */
      shift_adjusted_deviation: number | null;
    };
    /** EmployeeShiftRequest */
    EmployeeShiftRequest: {
      /** Employee Id */
      employee_id: string;
      /**
       * Start
       * Format: date-time
       */
      start: string;
      /**
       * End
       * Format: date-time
       */
      end: string;
      normalized_role: components['schemas']['OperationalRole'];
    };
    /** ErrorBody */
    ErrorBody: {
      /** Code */
      code: string;
      /** Message */
      message: string;
      /**
       * Details
       * @default []
       */
      details: components['schemas']['ErrorDetail'][];
    };
    /** ErrorDetail */
    ErrorDetail: {
      /** Code */
      code: string;
      /** Path */
      path: string;
      /** Message */
      message: string;
    };
    /** ErrorResponse */
    ErrorResponse: {
      error: components['schemas']['ErrorBody'];
    };
    /** FairnessMetricsResponse */
    FairnessMetricsResponse: {
      /** Participating Employee Count */
      participating_employee_count: number;
      /** Total Assignments */
      total_assignments: number;
      /** Average Flights */
      average_flights: number;
      /** Highest Flight Count */
      highest_flight_count: number;
      /** Lowest Flight Count */
      lowest_flight_count: number;
      /** Flight Count Spread */
      flight_count_spread: number;
      /** Maximum Consecutive Streak */
      maximum_consecutive_streak: number;
      /** Adjusted Workload Spread */
      adjusted_workload_spread: number | null;
      /** Total Participating Shift Minutes */
      total_participating_shift_minutes: number;
      /** Total Shift Adjusted Deviation */
      total_shift_adjusted_deviation: number;
    };
    /** FixedAssignmentRequest */
    FixedAssignmentRequest: {
      /** Employee Id */
      employee_id: string;
      flight: components['schemas']['FlightReferenceRequest'];
    };
    /** FlightAssignmentResponse */
    FlightAssignmentResponse: {
      flight: components['schemas']['FlightResponse'];
      flight_type: components['schemas']['FlightType'];
      /**
       * Work Start
       * Format: date-time
       */
      work_start: string;
      /**
       * Work End
       * Format: date-time
       */
      work_end: string;
      /** Assigned Employee Ids */
      assigned_employee_ids: string[];
      /** Fixed Employee Ids */
      fixed_employee_ids: string[];
      /** Staffing Count */
      staffing_count: number;
      /** Minimum Staff */
      minimum_staff: number;
      /** Preferred Staff */
      preferred_staff: number;
      /** Maximum Staff */
      maximum_staff: number;
      staffing_status: components['schemas']['StaffingStatus'];
      /** Minimum Met */
      minimum_met: boolean;
      /** Minimum Shortfall */
      minimum_shortfall: number;
      /** Preferred Met */
      preferred_met: boolean;
      /** Preferred Shortfall */
      preferred_shortfall: number;
      /** Express */
      express: boolean;
      /** Heavy */
      heavy: boolean;
      /** Push Covered */
      push_covered: boolean | null;
      /** Close Covered */
      close_covered: boolean | null;
      /** Warnings */
      warnings: components['schemas']['ScheduleWarningResponse'][];
    };
    /** FlightCorrectionAuditResponse */
    FlightCorrectionAuditResponse: {
      /**
       * Row Id
       * Format: uuid
       */
      row_id: string;
      /** Changes */
      changes: [string, string | boolean | null][];
      /** Original Values */
      original_values: [string, string | boolean | null][];
    };
    /** FlightCorrectionRequest */
    FlightCorrectionRequest: {
      /**
       * Row Id
       * Format: uuid
       */
      row_id: string;
      /** Arrival Flight Number */
      arrival_flight_number?: string | null;
      /** Departure Flight Number */
      departure_flight_number?: string | null;
      /** Arrival Time */
      arrival_time?: string | null;
      /** Departure Time */
      departure_time?: string | null;
      /** Origin */
      origin?: string | null;
      /** Destination */
      destination?: string | null;
      /** Gate */
      gate?: string | null;
      status?: components['schemas']['FlightStatus'] | null;
      /** Heavy */
      heavy?: boolean | null;
      /** Excluded */
      excluded?: boolean | null;
    };
    /** FlightCorrectionsRequest */
    FlightCorrectionsRequest: {
      /** Revision */
      revision: number;
      /** Operational Date */
      operational_date?: string | null;
      /**
       * Flight Corrections
       * @default []
       */
      flight_corrections: components['schemas']['FlightCorrectionRequest'][];
    };
    /** FlightReferenceRequest */
    FlightReferenceRequest: {
      /** Arrival Flight Number */
      arrival_flight_number?: string | null;
      /** Departure Flight Number */
      departure_flight_number?: string | null;
    };
    /** FlightRequest */
    FlightRequest: {
      /** Arrival Flight Number */
      arrival_flight_number?: string | null;
      /** Arrival Time */
      arrival_time?: string | null;
      /** Departure Flight Number */
      departure_flight_number?: string | null;
      /** Departure Time */
      departure_time?: string | null;
      /** Gate */
      gate?: string | null;
      /**
       * Heavy
       * @default false
       */
      heavy: boolean;
    };
    /** FlightResponse */
    FlightResponse: {
      /** Arrival Flight Number */
      arrival_flight_number: string | null;
      /** Arrival Time */
      arrival_time: string | null;
      /** Departure Flight Number */
      departure_flight_number: string | null;
      /** Departure Time */
      departure_time: string | null;
      /** Gate */
      gate: string | null;
      /** Heavy */
      heavy: boolean;
    };
    /** FlightReviewRowResponse */
    FlightReviewRowResponse: {
      /** Movement Type */
      movement_type?: string | null;
      /** Express */
      express?: boolean | null;
      /** Work Start */
      work_start?: string | null;
      /** Work End */
      work_end?: string | null;
      /** Confirmation Eligible */
      confirmation_eligible: boolean;
      /** Will Be Excluded */
      will_be_excluded: boolean;
      /** Correctable Fields */
      correctable_fields: string[];
      /**
       * Row Id
       * Format: uuid
       */
      row_id: string;
      /** Source Row */
      source_row: number;
      flight: components['schemas']['FlightValuesResponse'];
      /** Origin */
      origin: string | null;
      /** Destination */
      destination: string | null;
      status: components['schemas']['FlightStatus'];
      /** Excluded */
      excluded: boolean;
      /** Heavy Reviewed */
      heavy_reviewed: boolean;
      /** Notes Present */
      notes_present: boolean;
      /** Onward Time Present */
      onward_time_present: boolean;
      /** Late Arrival Section */
      late_arrival_section: boolean;
      /** Arrival Expected */
      arrival_expected: boolean;
      /** Departure Expected */
      departure_expected: boolean;
      /** Unresolved Fields */
      unresolved_fields: string[];
      /** Formula Fields */
      formula_fields: string[];
      /** Normalized Fields */
      normalized_fields: string[];
    };
    /**
     * FlightStatus
     * @enum {string}
     */
    FlightStatus: 'NORMAL' | 'TERMINATING' | 'AOG' | 'CANCELLED' | 'UNKNOWN';
    /** FlightTimePolicyRequest */
    FlightTimePolicyRequest: {
      /** Airport Timezone */
      airport_timezone: string;
      /**
       * Operational Day Start
       * Format: time
       */
      operational_day_start: string;
      /**
       * Planning Basis
       * @enum {string}
       */
      planning_basis: 'SCHEDULED' | 'ESTIMATED';
    };
    /**
     * FlightType
     * @description Movement types inferred from consistently populated directional sides.
     * @enum {string}
     */
    FlightType: 'ARRIVAL_ONLY' | 'DEPARTURE_ONLY' | 'TURN';
    /** FlightValuesResponse */
    FlightValuesResponse: {
      /** Arrival Flight Number */
      arrival_flight_number: string | null;
      /** Departure Flight Number */
      departure_flight_number: string | null;
      /** Arrival Time */
      arrival_time: string | null;
      /** Departure Time */
      departure_time: string | null;
      /** Gate */
      gate: string | null;
      /** Heavy */
      heavy: boolean;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** HealthResponse */
    HealthResponse: {
      /** Status */
      status: string;
    };
    /** ImportIssueResponse */
    ImportIssueResponse: {
      /** Code */
      code: string;
      severity: components['schemas']['IssueSeverity'];
      /** Message */
      message: string;
      /** Source Row */
      source_row?: number | null;
      /** Field */
      field?: string | null;
      /** Blocks Confirmation */
      blocks_confirmation: boolean;
      /** Remediation */
      remediation?: string | null;
    };
    /** ImportPreviewResponse */
    ImportPreviewResponse: {
      /**
       * Flight Rows
       * @default []
       */
      flight_rows: components['schemas']['FlightReviewRowResponse'][];
      flight_policy?: components['schemas']['FlightTimePolicyRequest'] | null;
      /**
       * Flight Corrections
       * @default []
       */
      flight_corrections: components['schemas']['FlightCorrectionAuditResponse'][];
      /** Operational Date Correction */
      operational_date_correction?: [string, string] | null;
      /** Revision */
      revision: number;
      /**
       * Operational Date
       * Format: date
       */
      operational_date: string;
      /** Detected Operational Dates */
      detected_operational_dates: string[];
      /** Roster */
      roster: components['schemas']['EmployeeRequest'][];
      /** Employees */
      employees: components['schemas']['EmployeeRequest'][];
      /** Rows */
      rows: components['schemas']['ReviewRowResponse'][];
      /** Matched Employee Ids */
      matched_employee_ids: string[];
      /** Unmatched Row Ids */
      unmatched_row_ids: string[];
      /** Ambiguous Row Ids */
      ambiguous_row_ids: string[];
      /** Vacancy Row Ids */
      vacancy_row_ids: string[];
      /** Issues */
      issues: components['schemas']['ImportIssueResponse'][];
      /** Source Issues */
      source_issues: components['schemas']['ImportIssueResponse'][];
      /** Confirmation Eligible */
      confirmation_eligible: boolean;
      /** Confirmation Blockers */
      confirmation_blockers: components['schemas']['ImportIssueResponse'][];
      /**
       * Optimization Eligible
       * @default false
       * @constant
       */
      optimization_eligible: false;
      /** Optimization Blockers */
      optimization_blockers: components['schemas']['ImportIssueResponse'][];
      config: components['schemas']['OptimizerConfigRequest'];
      /** Role Mappings */
      role_mappings: [string, components['schemas']['OperationalRole']][];
      /**
       * Discarded Sensitive Fields
       * @default [
       *       "notes",
       *       "unmatched_employee_names"
       *     ]
       */
      discarded_sensitive_fields: string[];
    };
    /** ImportReadinessResponse */
    ImportReadinessResponse: {
      /**
       * Operational Day Id
       * Format: uuid
       */
      operational_day_id: string;
      /** Confirmed Employee Schedule */
      confirmed_employee_schedule: boolean;
      /** Confirmed Flight Log */
      confirmed_flight_log: boolean;
      /** Both Inputs Confirmed */
      both_inputs_confirmed: boolean;
      /** Unresolved Blocking Issues */
      unresolved_blocking_issues: boolean;
      /** Optimization Eligible */
      optimization_eligible: boolean;
    };
    /** ImportResponse */
    ImportResponse: {
      /**
       * Accepted Flight Count
       * @default 0
       */
      accepted_flight_count: number;
      /**
       * Import Id
       * Format: uuid
       */
      import_id: string;
      import_type: components['schemas']['ImportType'];
      status: components['schemas']['ImportStatus'];
      /** Original Filename */
      original_filename: string;
      /** Media Type */
      media_type: string;
      /** Byte Size */
      byte_size: number;
      /** Sha256 */
      sha256: string;
      /** Schema Version */
      schema_version: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Confirmed At */
      confirmed_at: string | null;
      /** Confirmed Operational Day Id */
      confirmed_operational_day_id: string | null;
      /** Fatal Count */
      fatal_count: number;
      /** Error Count */
      error_count: number;
      /** Warning Count */
      warning_count: number;
      /** Accepted Shift Count */
      accepted_shift_count: number;
      /** Vacancy Count */
      vacancy_count: number;
      /** Unresolved Row Count */
      unresolved_row_count: number;
      preview: components['schemas']['ImportPreviewResponse'];
    };
    /**
     * ImportStatus
     * @enum {string}
     */
    ImportStatus: 'REVIEW_REQUIRED' | 'READY_TO_CONFIRM' | 'REJECTED' | 'CONFIRMED';
    /**
     * ImportType
     * @enum {string}
     */
    ImportType: 'TEAMWORK_EMPLOYEE_SCHEDULE' | 'DAILY_FLIGHT_LOG';
    /** InputVersionResponse */
    InputVersionResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Operational Date
       * Format: date
       */
      operational_date: string;
      /** Version Number */
      version_number: number;
      /** Parent Version Id */
      parent_version_id: string | null;
      /** Source Snapshot Id */
      source_snapshot_id: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Content Hash */
      content_hash: string;
      input: components['schemas']['OptimizationRequest'];
      /** Reason */
      reason: string | null;
      /** Warnings */
      warnings: components['schemas']['ValidationIssueResponse'][];
      /**
       * Valid
       * @default true
       */
      valid: boolean;
    };
    /**
     * IssueSeverity
     * @description Severity for structured spreadsheet-import issues.
     * @enum {string}
     */
    IssueSeverity: 'WARNING' | 'ERROR' | 'FATAL';
    /** JobCreateRequest */
    JobCreateRequest: {
      /**
       * Operational Day Version Id
       * Format: uuid
       */
      operational_day_version_id: string;
      /** Idempotency Key */
      idempotency_key: string;
      config?: components['schemas']['OptimizerConfigRequest'] | null;
      /**
       * Timeout Seconds
       * @default 180
       */
      timeout_seconds: number;
    };
    /** JobProgress */
    JobProgress: {
      /** Phase */
      phase: string;
      /**
       * Pass Number
       * @default 0
       */
      pass_number: number;
      /**
       * Stage Number
       * @default 0
       */
      stage_number: number;
      /** Stage Name */
      stage_name?: string | null;
      /** Solver Status */
      solver_status?: string | null;
    };
    /** JobResponse */
    JobResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Status
       * @enum {string}
       */
      status:
        'QUEUED' | 'RUNNING' | 'CANCELLING' | 'SUCCEEDED' | 'FAILED' | 'CANCELLED' | 'TIMED_OUT';
      /**
       * Operational Day Id
       * Format: uuid
       */
      operational_day_id: string;
      /** Operational Day Version Id */
      operational_day_version_id: string | null;
      /** Input Hash */
      input_hash: string;
      config: components['schemas']['OptimizerConfigRequest'];
      /** Timeout Seconds */
      timeout_seconds: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Started At */
      started_at: string | null;
      /** Finished At */
      finished_at: string | null;
      progress: components['schemas']['JobProgress'];
      /** Error Code */
      error_code: string | null;
      /** Result Run Id */
      result_run_id: string | null;
      /** Has Partial Result */
      has_partial_result: boolean;
    };
    /** JobResultResponse */
    JobResultResponse: {
      /**
       * Job Id
       * Format: uuid
       */
      job_id: string;
      /**
       * Status
       * @enum {string}
       */
      status:
        'QUEUED' | 'RUNNING' | 'CANCELLING' | 'SUCCEEDED' | 'FAILED' | 'CANCELLED' | 'TIMED_OUT';
      /** Partial */
      partial: boolean;
      /** Result Run Id */
      result_run_id: string | null;
      result: components['schemas']['OptimizationResponse'];
    };
    /** ObjectiveValueResponse */
    ObjectiveValueResponse: {
      /** Stage */
      stage: number;
      /** Name */
      name: string;
      /** Value */
      value: number;
      /** Proven Optimal */
      proven_optimal: boolean;
    };
    /** OperationalDayListResponse */
    OperationalDayListResponse: {
      /** Items */
      items: components['schemas']['OperationalDaySummaryResponse'][];
      /** Total */
      total: number;
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
    };
    /** OperationalDayRequest */
    OperationalDayRequest: {
      /**
       * Operational Date
       * Format: date
       */
      operational_date: string;
      /**
       * Employees
       * @default []
       */
      employees: components['schemas']['EmployeeRequest'][];
      /**
       * Employee Shifts
       * @default []
       */
      employee_shifts: components['schemas']['EmployeeShiftRequest'][];
      /**
       * Flights
       * @default []
       */
      flights: components['schemas']['FlightRequest'][];
      /**
       * Fixed Assignments
       * @default []
       */
      fixed_assignments: components['schemas']['FixedAssignmentRequest'][];
    };
    /** OperationalDayResourceResponse */
    OperationalDayResourceResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Operational Date
       * Format: date
       */
      operational_date: string;
      /**
       * Created At Utc
       * Format: date-time
       */
      created_at_utc: string;
      /** Input Schema Version */
      input_schema_version: number;
      /** Input Hash */
      input_hash: string;
      /** Employee Count */
      employee_count: number;
      /** Shift Count */
      shift_count: number;
      /** Flight Count */
      flight_count: number;
      /** Fixed Assignment Count */
      fixed_assignment_count: number;
      /**
       * Optimization Eligible
       * @default true
       */
      optimization_eligible: boolean;
      /**
       * Optimization Blockers
       * @default []
       */
      optimization_blockers: string[];
      input: components['schemas']['OptimizationRequest'];
    };
    /** OperationalDaySummaryResponse */
    OperationalDaySummaryResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Operational Date
       * Format: date
       */
      operational_date: string;
      /**
       * Created At Utc
       * Format: date-time
       */
      created_at_utc: string;
      /** Input Schema Version */
      input_schema_version: number;
      /** Input Hash */
      input_hash: string;
      /** Employee Count */
      employee_count: number;
      /** Shift Count */
      shift_count: number;
      /** Flight Count */
      flight_count: number;
      /** Fixed Assignment Count */
      fixed_assignment_count: number;
      /**
       * Optimization Eligible
       * @default true
       */
      optimization_eligible: boolean;
      /**
       * Optimization Blockers
       * @default []
       */
      optimization_blockers: string[];
    };
    /**
     * OperationalReadinessStatus
     * @description Operational meaning of a returned computational result.
     * @enum {string}
     */
    OperationalReadinessStatus:
      'READY' | 'READY_WITH_WARNINGS' | 'MANUAL_INTERVENTION_REQUIRED' | 'NO_USABLE_SCHEDULE';
    /**
     * OperationalRole
     * @description Normalized operational meaning of a source schedule position.
     * @enum {string}
     */
    OperationalRole:
      'RAMP_AGENT' | 'RAMP_LEAD' | 'POSSIBLE_RAMP_SUPPORT' | 'TRAINEE' | 'NON_RAMP' | 'UNKNOWN';
    /** OptimizationAttemptResponse */
    OptimizationAttemptResponse: {
      /** Included Leads */
      included_leads: boolean;
      status: components['schemas']['OptimizationStatus'];
      /** Minimum Staffed Flights */
      minimum_staffed_flights: number;
      /** Qualification Compliant Flights */
      qualification_compliant_flights: number;
      /** Lead Assignments */
      lead_assignments: number;
      /** Critical Shortage Count */
      critical_shortage_count: number;
      /** Lead Candidate Count */
      lead_candidate_count: number;
      /** Solver Runtime Seconds */
      solver_runtime_seconds: number;
      /** Pass Number */
      pass_number: number;
      /** Attempt Label */
      attempt_label: string;
      /** Usable Schedule */
      usable_schedule: boolean;
      /** Selected As Final */
      selected_as_final: boolean;
      /** Known Unsatisfied Required Break Count */
      known_unsatisfied_required_break_count: number;
      /** Objective Stages Completed */
      objective_stages_completed: number;
      /** All Objectives Proven Optimal */
      all_objectives_proven_optimal: boolean;
    };
    /** OptimizationRequest */
    OptimizationRequest: {
      operational_day: components['schemas']['OperationalDayRequest'];
      config?: components['schemas']['OptimizerConfigRequest'];
    };
    /** OptimizationResponse */
    OptimizationResponse: {
      status: components['schemas']['OptimizationStatus'];
      operational_readiness: components['schemas']['OperationalReadinessStatus'];
      emergency_staffing_status: components['schemas']['EmergencyStaffingStatus'];
      emergency_pass_disposition: components['schemas']['EmergencyPassDisposition'];
      /** Emergency Leads Enabled */
      emergency_leads_enabled: boolean;
      /** Emergency Lead Staffing Used */
      emergency_lead_staffing_used: boolean | null;
      /** Solver Runtime Seconds */
      solver_runtime_seconds: number;
      schedule_summary: components['schemas']['ScheduleSummaryResponse'] | null;
      /** Flight Results */
      flight_results: components['schemas']['FlightAssignmentResponse'][];
      /** Employee Results */
      employee_results: components['schemas']['EmployeeScheduleResponse'][];
      fairness_metrics: components['schemas']['FairnessMetricsResponse'] | null;
      continuity_metrics: components['schemas']['ContinuityMetricsResponse'] | null;
      /** Attempts */
      attempts: components['schemas']['OptimizationAttemptResponse'][];
      /** Objective Values */
      objective_values: components['schemas']['ObjectiveValueResponse'][];
      /** Warnings */
      warnings: components['schemas']['ScheduleWarningResponse'][];
      /** Lead Assignments */
      lead_assignments: components['schemas']['EmergencyLeadAssignmentResponse'][];
    };
    /** OptimizationRunListResponse */
    OptimizationRunListResponse: {
      /** Items */
      items: components['schemas']['OptimizationRunSummaryResponse'][];
      /** Total */
      total: number;
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
    };
    /** OptimizationRunResourceResponse */
    OptimizationRunResourceResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Operational Day Id
       * Format: uuid
       */
      operational_day_id: string;
      /**
       * Created At Utc
       * Format: date-time
       */
      created_at_utc: string;
      /** Package Version */
      package_version: string;
      /** Api Version */
      api_version: string;
      /** Result Schema Version */
      result_schema_version: number;
      /** Input Hash */
      input_hash: string;
      solver_status: components['schemas']['OptimizationStatus'];
      operational_readiness: components['schemas']['OperationalReadinessStatus'];
      emergency_pass_disposition: components['schemas']['EmergencyPassDisposition'];
      /** Solver Runtime Seconds */
      solver_runtime_seconds: number;
      /** Attempt Count */
      attempt_count: number;
      /** Objective Stage Count */
      objective_stage_count: number;
      /** Warning Count */
      warning_count: number;
      result: components['schemas']['OptimizationResponse'];
    };
    /** OptimizationRunSummaryResponse */
    OptimizationRunSummaryResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Operational Day Id
       * Format: uuid
       */
      operational_day_id: string;
      /**
       * Created At Utc
       * Format: date-time
       */
      created_at_utc: string;
      /** Package Version */
      package_version: string;
      /** Api Version */
      api_version: string;
      /** Result Schema Version */
      result_schema_version: number;
      /** Input Hash */
      input_hash: string;
      solver_status: components['schemas']['OptimizationStatus'];
      operational_readiness: components['schemas']['OperationalReadinessStatus'];
      emergency_pass_disposition: components['schemas']['EmergencyPassDisposition'];
      /** Solver Runtime Seconds */
      solver_runtime_seconds: number;
      /** Attempt Count */
      attempt_count: number;
      /** Objective Stage Count */
      objective_stage_count: number;
      /** Warning Count */
      warning_count: number;
    };
    /**
     * OptimizationStatus
     * @description High-level status exposed without leaking solver-specific constants.
     * @enum {string}
     */
    OptimizationStatus: 'OPTIMAL' | 'FEASIBLE' | 'INFEASIBLE' | 'UNKNOWN';
    /**
     * OptimizerConfigRequest
     * @description Every public optimizer setting, defaulted from the domain configuration.
     */
    OptimizerConfigRequest: {
      /**
       * Arrival Preparation Minutes
       * @default 10
       */
      arrival_preparation_minutes: number;
      /**
       * Arrival Offload Minutes
       * @default 20
       */
      arrival_offload_minutes: number;
      /**
       * Departure Work Minutes
       * @default 60
       */
      departure_work_minutes: number;
      /**
       * Minimum Staff
       * @default 3
       */
      minimum_staff: number;
      /**
       * Normal Preferred Staff
       * @default 4
       */
      normal_preferred_staff: number;
      /**
       * Heavy Preferred Staff
       * @default 5
       */
      heavy_preferred_staff: number;
      /**
       * Required Break Minutes
       * @default 30
       */
      required_break_minutes: number;
      /**
       * Consecutive Reset Minutes
       * @default 40
       */
      consecutive_reset_minutes: number;
      /**
       * Continuity Horizon Minutes
       * @default 120
       */
      continuity_horizon_minutes: number;
      /**
       * Express Threshold
       * @default 3000
       */
      express_threshold: number;
      /**
       * Express Workload Factor
       * @default 0.8
       */
      express_workload_factor: number;
      /**
       * Three Person Workload Multiplier
       * @default 1.15
       */
      three_person_workload_multiplier: number;
      /**
       * Workload Scale
       * @default 100
       */
      workload_scale: number;
      /**
       * Allow Leads For Minimum Staffing
       * @default false
       */
      allow_leads_for_minimum_staffing: boolean;
      /**
       * Allow Trainees For Assignments
       * @default false
       */
      allow_trainees_for_assignments: boolean;
      /**
       * Allow Possible Ramp Support For Assignments
       * @default false
       */
      allow_possible_ramp_support_for_assignments: boolean;
      /**
       * Solver Time Limit Seconds
       * @default 30
       */
      solver_time_limit_seconds: number;
      /**
       * Solver Random Seed
       * @default 42
       */
      solver_random_seed: number;
      /**
       * Solver Num Search Workers
       * @default 1
       */
      solver_num_search_workers: number;
    };
    /**
     * Qualification
     * @description Authoritative qualifications supplied independently of schedule roles.
     * @enum {string}
     */
    Qualification: 'PUSH' | 'CLOSE_OUT';
    /** ReviewRowResponse */
    ReviewRowResponse: {
      /**
       * Row Id
       * Format: uuid
       */
      row_id: string;
      /** Source Row */
      source_row: number;
      /** Employee Id */
      employee_id: string | null;
      /** Employee Name */
      employee_name?: string | null;
      /** Start */
      start: string | null;
      /** End */
      end: string | null;
      normalized_role: components['schemas']['OperationalRole'];
      /** Vacancy */
      vacancy: boolean;
      /** Excluded */
      excluded: boolean;
      /** Notes Present */
      notes_present: boolean;
      /** Swapboard */
      swapboard: boolean | null;
      /**
       * Match Status
       * @enum {string}
       */
      match_status: 'MATCHED' | 'VACANCY' | 'UNMATCHED_EMPLOYEE' | 'AMBIGUOUS_EMPLOYEE';
      /** Formula Fields */
      formula_fields: string[];
      /** Required Fields Missing */
      required_fields_missing: string[];
      /** Source Date */
      source_date: string | null;
      /** Imported Hours */
      imported_hours: number | null;
    };
    /** RevisionRequest */
    RevisionRequest: {
      /** Idempotency Key */
      idempotency_key: string;
      /** Expected Parent Hash */
      expected_parent_hash: string;
      input: components['schemas']['OptimizationRequest'];
      /** Reason */
      reason?: string | null;
    };
    /** RowCorrectionRequest */
    RowCorrectionRequest: {
      /**
       * Row Id
       * Format: uuid
       */
      row_id: string;
      /** Employee Id */
      employee_id?: string | null;
      /** Start */
      start?: string | null;
      /** End */
      end?: string | null;
      normalized_role?: components['schemas']['OperationalRole'] | null;
      /** Excluded */
      excluded?: boolean | null;
      /** Vacancy */
      vacancy?: boolean | null;
      /** Enabled */
      enabled?: boolean | null;
      /** Qualifications */
      qualifications?: components['schemas']['Qualification'][] | null;
    };
    /** ScheduleSummaryResponse */
    ScheduleSummaryResponse: {
      /** Total Flights */
      total_flights: number;
      /** Minimum Staffed Flights */
      minimum_staffed_flights: number;
      /** Below Minimum Flights */
      below_minimum_flights: number;
      /** Preferred Staffed Flights */
      preferred_staffed_flights: number;
      /** Qualification Required Flights */
      qualification_required_flights: number;
      /** Qualification Compliant Flights */
      qualification_compliant_flights: number;
      /** Missing Push Flights */
      missing_push_flights: number;
      /** Missing Close Out Flights */
      missing_close_out_flights: number;
      /** Participating Employee Count */
      participating_employee_count: number;
      /** Employees With Satisfied Break */
      employees_with_satisfied_break: number;
      /** Employees With Unsatisfied Break */
      employees_with_unsatisfied_break: number;
      /** Employees With Nonevaluable Break */
      employees_with_nonevaluable_break: number;
      /** Total Assignments */
      total_assignments: number;
      /** Emergency Lead Assignments */
      emergency_lead_assignments: number;
      /** Critical Warning Count */
      critical_warning_count: number;
      /** Warning Count */
      warning_count: number;
      /** All Objectives Proven Optimal */
      all_objectives_proven_optimal: boolean;
    };
    /** ScheduleWarningResponse */
    ScheduleWarningResponse: {
      code: components['schemas']['WarningCode'];
      severity: components['schemas']['WarningSeverity'];
      /** Message */
      message: string;
      /** Arrival Flight Number */
      arrival_flight_number: string | null;
      /** Departure Flight Number */
      departure_flight_number: string | null;
      /** Employee Id */
      employee_id: string | null;
    };
    /**
     * StaffingStatus
     * @description Operational staffing status for one flight.
     * @enum {string}
     */
    StaffingStatus: 'PREFERRED_STAFFED' | 'MINIMUM_STAFFED' | 'BELOW_MINIMUM';
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /** ValidationIssueResponse */
    ValidationIssueResponse: {
      /** Code */
      code: string;
      /** Path */
      path: string;
      /** Message */
      message: string;
    };
    /** ValidationResponse */
    ValidationResponse: {
      /** Valid */
      valid: boolean;
      /** Issues */
      issues: components['schemas']['ValidationIssueResponse'][];
    };
    /** VersionResponse */
    VersionResponse: {
      /** Api Version */
      api_version: string;
      /** Package Version */
      package_version: string;
    };
    /**
     * WarningCode
     * @description Stable warning identifiers for reporting and future API clients.
     * @enum {string}
     */
    WarningCode:
      | 'MINIMUM_STAFFING_NOT_MET'
      | 'PUSH_QUALIFICATION_NOT_MET'
      | 'CLOSE_QUALIFICATION_NOT_MET'
      | 'REQUIRED_BREAK_NOT_MET'
      | 'EMERGENCY_LEAD_USED'
      | 'LEAD_STAFFING_REQUIRED'
      | 'LEAD_QUALIFICATION_REQUIRED'
      | 'CRITICAL_SHORTAGE_REMAINS'
      | 'MANUAL_INTERVENTION_REQUIRED'
      | 'SOLVER_RESULT_NOT_PROVEN_OPTIMAL'
      | 'EMERGENCY_RECOVERY_NOT_ADOPTED'
      | 'NO_USABLE_SCHEDULE';
    /**
     * WarningSeverity
     * @description Severity of a supervisor-facing schedule warning.
     * @enum {string}
     */
    WarningSeverity: 'INFO' | 'WARNING' | 'CRITICAL';
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  combine_imports_api_v1_imports_combine_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CombineImportsRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ImportReadinessResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  readiness_api_v1_imports_operational_days__day_id__readiness_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        day_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ImportReadinessResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  upload_flights_api_v1_imports_daily_flight_log_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_upload_flights_api_v1_imports_daily_flight_log_post'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ImportResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  upload_schedule_api_v1_imports_teamwork_employee_schedule_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_upload_schedule_api_v1_imports_teamwork_employee_schedule_post'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ImportResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_import_api_v1_imports__import_id__preview_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        import_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ImportResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_import_api_v1_imports__import_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        import_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ImportResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_revision_api_v1_imports__import_id__revisions__revision__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        import_id: string;
        revision: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ImportResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  correct_import_api_v1_imports__import_id__corrections_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        import_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json':
          | components['schemas']['CorrectionsRequest']
          | components['schemas']['FlightCorrectionsRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ImportResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  confirm_import_api_v1_imports__import_id__confirm_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        import_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ConfirmImportRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ImportResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_api_v1_operational_days__day__drafts_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        day: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DraftRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['InputVersionResponse'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  listing_api_v1_operational_days__day__versions_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path: {
        day: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['InputVersionResponse'][];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  get_api_v1_operational_day_versions__version_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        version_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['InputVersionResponse'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  revise_api_v1_operational_day_versions__version_id__revisions_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        version_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RevisionRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['InputVersionResponse'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  create_api_v1_optimization_jobs_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['JobCreateRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JobResponse'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  status_api_v1_optimization_jobs__job_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JobResponse'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  progress_api_v1_optimization_jobs__job_id__progress_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JobProgress'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  cancel_api_v1_optimization_jobs__job_id__cancel_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JobResponse'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  result_api_v1_optimization_jobs__job_id__result_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JobResultResponse'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  health_api_v1_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponse'];
        };
      };
    };
  };
  package_version_api_v1_version_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VersionResponse'];
        };
      };
    };
  };
  validate_day_api_v1_operational_days_validate_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['OptimizationRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ValidationResponse'];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  optimize_api_v1_optimizations_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['OptimizationRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JobResponse'];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  list_stored_days_api_v1_operational_days_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
        operational_date?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OperationalDayListResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_stored_day_api_v1_operational_days_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['OptimizationRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OperationalDayResourceResponse'];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorResponse'];
        };
      };
    };
  };
  get_stored_day_api_v1_operational_days__operational_day_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        operational_day_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OperationalDayResourceResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  optimize_stored_day_api_v1_operational_days__operational_day_id__optimizations_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        operational_day_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JobResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_stored_runs_api_v1_operational_days__operational_day_id__optimization_runs_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path: {
        operational_day_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OptimizationRunListResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_stored_run_api_v1_optimization_runs__optimization_run_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        optimization_run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OptimizationRunResourceResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
